@startuml 並列処理
title シーフードカレーを作る

start

:野菜を洗う;
fork
fork
:シーフードミックスを半解凍する;
:フライパンにシーフードミックスを入れ中火にする;
note right
白ワインを使い、程よいかんじになるまで
end note
:弱火にして蓋をする;
note right
2分間、蒸し焼きにする
end note
fork again
:野菜を切る;
end fork
:鍋に野菜・シーフードミックスを入れて炒め、水を入れて煮込む;
:カレールーを入れる;
note right
ひとにたちしてから火を止める
そしてからカレールーを入れとろみがついたら2,3分間煮る
end note
fork again
:炊飯器に電源をONにする;
:米を洗う;
:米を炊く;
end fork
:ご飯に乗せて完成！;
stop
@enduml