@startuml ステートマシン図
    left to right direction
    state メニュー
    state 予約と確認
    state あなたの順番
    state 今の順番

    [*] --> メニュー
    メニュー --> 予約と確認 : 登録ボタンを押す
    予約と確認 --> あなたの順番 : 名前と電話番号が記録される
    予約と確認 --> あなたの順番 : 確認ボタンを押す
    メニュー <-- 予約と確認 : 取消ボタンを押す
    あなたの順番 --> メニュー : メニューボタンを押す
    メニュー --> 今の順番 : 今の順番ボタンを押す
    メニュー <-- 今の順番 : メニューボタンを押す
    メニュー --> [*]
@enduml