@startuml 演習2-5
    actor 利用者 #FFFFFF;line:SkyBlue;line.bold;
    rectangle ホテル{
        usecase ログインする
        usecase (<u>予約する</u>\n拡張点\nキャンペーン期間) as input
        usecase キャンペーン
        }
    input .> ログインする : <<include>>
    キャンペーン .> input : <<extend>>
    input <-- 利用者
@enduml