@startuml クラス図
    left to right direction
    class ライントレーサー{
    ---
    }

    class 光センサー{
    ---
    }

    class 右モータ{
    ---
    }

    class 左モータ{
    ---
    }

    class CPU{
    ---
    }

    class 電源SW{
    ---
    }

    電源SW --> CPU : > 起動する
    CPU --> ライントレーサー
    ライントレーサー -- 右モータ : > 指示する
    ライントレーサー -- 光センサー : > 感知する
    ライントレーサー -- 左モータ : > 指示する

@enduml