@startuml 演習5
    left to right direction
    actor 販売部 #FFFFFF;line:SkyBlue;line.bold;
    rectangle 販売管理システム{
        usecase 注文商品を確認する
        usecase 商品の出荷状況を登録する
    }
    販売部 --> 注文商品を確認する : システムで確認
    販売部 --> 商品の出荷状況を登録する : システムで確認
@enduml